# Generated by Django 5.1.7 on 2025-03-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='user_id',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cargo',
            name='payment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='shipment_id',
            field=models.CharField(default='q', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
