# Generated by Django 4.2.20 on 2025-04-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-04-15 12:00'),
            preserve_default=False,
        ),
    ]
