# Generated by Django 4.2.20 on 2025-04-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_cargo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='payment',
            field=models.CharField(max_length=255),
        ),
    ]
