# Generated by Django 5.1.7 on 2025-03-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_remove_cargo_image_cargo_distance_cargo_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='payment',
            field=models.CharField(default='Default Payment', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargo',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
