# Generated by Django 5.1.7 on 2025-03-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_cargo_company_cargo_description_cargo_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_description', models.CharField(max_length=255)),
                ('customer_location', models.CharField(max_length=255)),
                ('customer_location_url', models.CharField(max_length=255, null=True)),
                ('customer_web_site', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cargo',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=9999, null=True, unique=True),
        ),
    ]
