# Generated by Django 4.2.20 on 2025-04-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_alter_cargo_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='currency',
            field=models.CharField(default='1', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargo',
            name='payment_method',
            field=models.CharField(default='q', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargo',
            name='truck',
            field=models.CharField(default='qw', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cargo',
            name='payment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
