# Generated by Django 4.2.20 on 2025-04-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_cargo_currency_cargo_payment_method_cargo_truck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='truck',
            field=models.CharField(max_length=100),
        ),
    ]
