# Generated by Django 4.2.20 on 2025-04-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0005_alter_cargo_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='payment',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
    ]
