# Generated by Django 5.1.7 on 2025-03-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
