# Generated by Django 5.1.7 on 2025-03-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0006_alter_cargo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='shipment_id',
            field=models.CharField(blank=True, default='N/A', max_length=9999, null=True, unique=True),
        ),
    ]
