# Generated by Django 5.1.7 on 2025-03-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0007_alter_cargo_shipment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='shipment_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
