# Generated by Django 5.1.7 on 2025-03-18 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0008_alter_cargo_phone_alter_cargo_shipment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_hash',
            field=models.CharField(default=' ', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
