# Generated by Django 5.1.7 on 2025-03-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0009_cargo_customer_customer_phone_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_location_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_web_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
