# Generated by Django 5.1.7 on 2025-03-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0010_alter_customer_customer_location_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
