# Generated by Django 5.1.7 on 2025-03-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0011_alter_customer_phone_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=' ', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
