# Generated by Django 5.1.7 on 2025-03-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0012_customer_phone_alter_customer_phone_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
