# Generated by Django 5.1.7 on 2025-03-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0013_alter_customer_phone_hash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_hash',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=9999, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_location_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_web_site',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
