# Generated by Django 5.1.7 on 2025-03-19 11:10
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ("cargo", "0014_delete_product_remove_cargo_customer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="phone_hash",
        ),
    ]